# Generated by Django 5.2.9 on 2026-01-19 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_original', models.CharField(blank=True, max_length=200, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('release_date', models.DateField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска')),
                ('status', models.CharField(choices=[('ongoing', 'В процессе'), ('completed', 'Завершено'), ('planned', 'Запланировано'), ('on_hold', 'Приостановлено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг')),
                ('duration_per_episode', models.IntegerField(default=24, verbose_name='Длительность эпизода (мин)')),
                ('total_episodes', models.IntegerField(default=0, verbose_name='Всего эпизодов')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адрес')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voice_actors/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Актер озвучки',
                'verbose_name_plural': 'Актеры озвучки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер эпизода')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название эпизода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.CharField(default='24:00', max_length=10, verbose_name='Длительность')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='hikkiinfo.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['anime', 'number'],
                'unique_together': {('anime', 'number')},
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime', to='hikkiinfo.genre', verbose_name='Жанры'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('name_original', models.CharField(blank=True, max_length=100, verbose_name='Оригинальное имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='hikkiinfo.anime', verbose_name='Аниме')),
                ('voice_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='hikkiinfo.voiceactor', verbose_name='Актер озвучки')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['anime', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2160p', '2160p (4K)')], max_length=10, verbose_name='Качество')),
                ('video_url', models.URLField(verbose_name='URL видео')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='Размер файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_qualities', to='hikkiinfo.episode', verbose_name='Эпизод')),
            ],
            options={
                'verbose_name': 'Качество видео',
                'verbose_name_plural': 'Качества видео',
                'ordering': ['episode', '-quality'],
                'unique_together': {('episode', 'quality')},
            },
        ),
    ]
