# Generated by Django 5.2.9 on 2026-01-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikkiinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бэкапа')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байт)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Резервная копия БД',
                'verbose_name_plural': 'Резервные копии БД',
                'ordering': ['-created_at'],
            },
        ),
    ]
